# Generated by Django 4.1.3 on 2022-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='website_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
