# Generated by Django 4.1.3 on 2022-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_reason_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='animal',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('bird', 'bird'), ('fish', 'fish'), ('reptile', 'reptile'), ('other', 'other')], default='dog', max_length=50),
        ),
    ]
