# Generated by Django 4.1.3 on 2022-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_confirmed_alter_user_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='report',
            name='valid',
            field=models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
